# Generated by Django 5.1.2 on 2024-11-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.IntegerField()),
                ('pr_name', models.CharField(max_length=100)),
                ('pr_image', models.ImageField(upload_to='pic')),
                ('pr_description', models.TextField()),
            ],
        ),
    ]
