# Generated by Django 5.1.2 on 2024-11-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_logo_delete_product1'),
    ]

    operations = [
        migrations.CreateModel(
            name='myProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=100)),
                ('pr_image', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.DeleteModel(
            name='logo',
        ),
    ]
