# Generated by Django 5.1.2 on 2024-11-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_myproduct_delete_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='my',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.DeleteModel(
            name='myProduct',
        ),
    ]
