# Generated by Django 5.1.2 on 2024-11-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_my_delete_myproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.DeleteModel(
            name='my',
        ),
    ]
