# Generated by Django 5.1.2 on 2024-11-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_compare_delete_my'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('i_image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
