# Generated by Django 5.1.2 on 2024-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_iphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iphonepro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
