# Generated by Django 5.1.2 on 2024-11-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_iphonepro'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonepro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('Features', models.CharField(max_length=20)),
                ('F_name', models.TextField(max_length=1000)),
                ('InTheBox', models.CharField(max_length=100)),
                ('I_name', models.CharField(max_length=100)),
                ('Warranty', models.CharField(max_length=50)),
                ('W_name', models.CharField(max_length=100)),
            ],
        ),
    ]
