# Generated by Django 5.1.2 on 2024-11-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_phonepro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonepro',
            name='F_name',
            field=models.TextField(max_length=3000),
        ),
    ]
