# Generated by Django 5.1.2 on 2024-11-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='features',
            name='m_name',
        ),
    ]
