# Generated by Django 5.1.2 on 2024-11-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_myphone_remove_phonepro_f_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myphone',
            old_name='i_image',
            new_name='my_image',
        ),
    ]
