# Generated by Django 5.1.2 on 2024-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_rename_i_image_myphone_my_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='my',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
