# Generated by Django 5.1.2 on 2024-11-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0018_iphone15'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='iphone15',
            new_name='mm',
        ),
    ]
