# Generated by Django 5.1.2 on 2024-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0019_rename_iphone15_mm'),
    ]

    operations = [
        migrations.CreateModel(
            name='sari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
