# Generated by Django 5.1.2 on 2024-11-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0022_bbb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('my_image', models.ImageField(upload_to='pic')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
