# Generated by Django 5.1.2 on 2024-11-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0026_regiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regiter',
        ),
    ]
