# Generated by Django 5.1.2 on 2024-11-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0029_cart_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
