# Generated by Django 5.1.2 on 2024-11-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0030_iphone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr_quanity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
