# Generated by Django 5.1.2 on 2024-11-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0031_product_pr_quanity'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='pr_quanity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
