# Generated by Django 5.1.3 on 2024-11-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0036_product_pr_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pr_trending',
            new_name='trending',
        ),
    ]
