# Generated by Django 5.1.2 on 2024-11-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0037_rename_pr_trending_product_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='iphoneplus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('my_image', models.ImageField(upload_to='pic')),
                ('price', models.CharField(max_length=20)),
                ('pr_quanity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='iplus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('InTheBox', models.CharField(max_length=100)),
                ('I_name', models.CharField(max_length=100)),
                ('Warranty', models.CharField(max_length=50)),
                ('W_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='plus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='plus16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.TextField(max_length=1000)),
                ('b_name', models.TextField(max_length=1000)),
                ('c_name', models.TextField(max_length=1000)),
                ('d_name', models.TextField(max_length=1000)),
                ('e_name', models.TextField(max_length=1000)),
                ('f_name', models.TextField(max_length=1000)),
                ('g_name', models.TextField(max_length=1000)),
                ('h_name', models.TextField(max_length=1000)),
                ('k_name', models.TextField(max_length=1000)),
            ],
        ),
    ]
