# Generated by Django 5.1.2 on 2024-12-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0042_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='pr_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.product'),
        ),
    ]
