# Generated by Django 5.1.2 on 2024-12-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0043_iphone_pr_id_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='mm',
            name='pr_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
