# Generated by Django 5.1.2 on 2024-12-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0045_ts_pr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphoneplus',
            name='pr_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
