# Generated by Django 5.1.2 on 2024-12-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0046_iphoneplus_pr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myphone',
            name='pr_id',
        ),
        migrations.RemoveField(
            model_name='myphone',
            name='pr_quanity',
        ),
    ]
