# Generated by Django 5.1.2 on 2024-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0048_myphone_pr_quanity'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphone',
            name='pr_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
