# Generated by Django 5.1.2 on 2024-12-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0049_myphone_pr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_id',
        ),
    ]
