# Generated by Django 5.1.2 on 2024-12-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0053_rename_user_cart_user_cart_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='User',
        ),
    ]
