# Generated by Django 5.1.2 on 2024-12-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0054_rename_user_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_added',
        ),
    ]
